select * from customers

-- populate cmer country id
UPDATE CUSTOMERS
JOIN LOCATIONS
ON customers.country = LOCATIONS.country_name
SET customers.country_id = LOCATIONS.country_id

-- remove region
ALTER TABLE CUSTOMERS
DROP COLUMN region

-- more data

INSERT INTO CUSTOMERS
	(forename, surname, email, city, country)
VALUES
('Romeo', 'Voden', 'rvoden0@alexa.com', 'Mpumalanga', 'South Africa'),
('Crista', 'Moehle', 'cmoehle1@opera.com', 'Tobias Fornier', 'Philippines'),
('Amalee', 'Bleue', 'ableue2@vinaora.com', 'Abbotsford', 'Canada'),
('Felecia', 'Daffern', 'fdaffern3@spotify.com', 'Mỏ Cày', 'Vietnam'),
('Florry', 'Gamon', 'fgamon4@reddit.com', 'Xiashan', 'China'),
('Hamel', 'Michele', 'hmichele5@ted.com', 'Poponcol', 'Indonesia'),
('Winnah', 'Patzelt', 'wpatzelt6@boston.com', 'Venustiano Carranza', 'Mexico'),
('Shaylah', 'Schulze', 'sschulze7@spiegel.de', 'Hotaka', 'Japan'),
('Sherri', 'O''Doghesty', 'sodoghesty8@princeton.edu', 'Bhokadoke', 'Indonesia'),
('Koralle', 'Summerlad', 'ksummerlad9@ning.com', 'Mirsk', 'Poland'),
('Cristy', 'Durgan', 'cdurgana@google.com', 'Kukulu', 'Indonesia'),
('Brig', 'Markey', 'bmarkeyb@admin.ch', 'Zárkos', 'Greece'),
('Morlee', 'Linguard', 'mlinguardc@drupal.org', 'Kolsh', 'Albania'),
('Kissie', 'Carbery', 'kcarberyd@chronoengine.com', 'Wulan Haye', 'China'),
('Obidiah', 'Brimley', 'obrimleye@gov.uk', 'Tiraspol', 'Moldova'),
('Mozes', 'Jeffrey', 'mjeffreyf@craigslist.org', 'Songkan', 'China'),
('Tiena', 'Gooders', 'tgoodersg@google.com', 'Pardubice', 'Czech Republic'),
('Avie', 'Pountain', 'apountainh@drupal.org', 'Jinchuan', 'China'),
('Wallie', 'Raubenheim', 'wraubenheimi@miibeian.gov.cn', 'São Roque', 'Brazil'),
('Rebe', 'Leale', 'rlealej@rediff.com', 'Nonsan', 'South Korea'),
('Morena', 'Edkins', 'medkinsk@blinklist.com', 'Arneiro', 'Portugal'),
('Tracee', 'Ainscough', 'tainscoughl@yellowbook.com', 'Sypniewo', 'Poland'),
('Christa', 'Peppard', 'cpeppardm@barnesandnoble.com', 'Jezzîne', 'Lebanon'),
('Ginnifer', 'Gaffer', 'ggaffern@forbes.com', 'Independencia', 'Mexico'),
('Gilberte', 'Francois', 'gfrancoiso@github.com', 'Kalodu', 'Indonesia'),
('Kynthia', 'Fydo', 'kfydop@auda.org.au', 'Irbid', 'Jordan'),
('Zebulon', 'Hallex', 'zhallexq@uol.com.br', 'Krajan Atas Suger Lor', 'Indonesia'),
('Rikki', 'Bunn', 'rbunnr@go.com', 'Agudos', 'Brazil'),
('Warner', 'Burrows', 'wburrowss@telegraph.co.uk', 'Sanbaishan', 'China'),
('Nathanial', 'Langman', 'nlangmant@economist.com', 'San Juan del Cesar', 'Colombia'),
('Sarita', 'Bartoloma', 'sbartolomau@ask.com', 'Qintong', 'China'),
('Franky', 'Grabbam', 'fgrabbamv@cornell.edu', 'Ise', 'Japan'),
('Eddie', 'Ivasyushkin', 'eivasyushkinw@merriam-webster.com', 'Ros’', 'Belarus'),
('Hortensia', 'Saunier', 'hsaunierx@xinhuanet.com', 'Mstów', 'Poland'),
('Janeva', 'Sandom', 'jsandomy@icq.com', 'Jenang Selatan', 'Indonesia'),
('Maddy', 'York', 'myorkz@goodreads.com', 'Burrel', 'Albania'),
('Teodora', 'Broader', 'tbroader10@sfgate.com', 'Balakhninskiy', 'Russia'),
('Halli', 'Affron', 'haffron11@networksolutions.com', 'Hörby', 'Sweden'),
('Gavra', 'Siverns', 'gsiverns12@nature.com', 'Beltinci', 'Slovenia'),
('Gilberte', 'Ferreira', 'gferreira13@cam.ac.uk', 'Khorramdarreh', 'Iran'),
('Wini', 'Foulkes', 'wfoulkes14@usda.gov', 'Novyye Gorki', 'Russia'),
('Nester', 'Egarr', 'negarr15@smugmug.com', 'Gävle', 'Sweden'),
('Cilka', 'Fibbens', 'cfibbens16@163.com', 'Independencia', 'Mexico'),
('Levy', 'Scotchmoor', 'lscotchmoor17@163.com', 'Sendai-shi', 'Japan'),
('Jeth', 'Digger', 'jdigger18@ucla.edu', 'Dąbrowa', 'Poland'),
('Alysa', 'Brandom', 'abrandom19@who.int', 'Zevgolateió', 'Greece'),
('Bekki', 'Guilloneau', 'bguilloneau1a@cafepress.com', 'Panyingkiran', 'Indonesia'),
('Antonino', 'Towey', 'atowey1b@mapy.cz', 'Sawin', 'Poland'),
('Arabele', 'Goforth', 'agoforth1c@illinois.edu', 'Krupanj', 'Serbia'),
('Wrennie', 'Studart', 'wstudart1d@mapy.cz', 'Juru', 'Brazil'),
('Ford', 'Bestall', 'fbestall1e@moonfruit.com', 'Morales', 'Colombia'),
('Michale', 'Stoppard', 'mstoppard1f@ihg.com', 'Bayangol', 'Mongolia'),
('Norean', 'Mettrick', 'nmettrick1g@163.com', 'Pueblo Viejo', 'Panama'),
('Reeba', 'Byforth', 'rbyforth1h@mtv.com', 'Ḩurayḑah', 'Yemen'),
('Filippa', 'Matthai', 'fmatthai1i@booking.com', 'Zhongxiang', 'China'),
('Ladonna', 'Gannicott', 'lgannicott1j@about.com', 'Libertad', 'Philippines'),
('Mahmud', 'McAnalley', 'mmcanalley1k@nyu.edu', 'Xihe', 'China'),
('Susette', 'Tedman', 'stedman1l@posterous.com', 'Danilov', 'Russia'),
('Shadow', 'Gribbell', 'sgribbell1m@alexa.com', 'Vetluzhskiy', 'Russia'),
('Alexandro', 'Mc Grath', 'amcgrath1n@economist.com', 'Budenovetc', 'Russia'),
('Brig', 'Tanton', 'btanton1o@mayoclinic.com', 'Antalaha', 'Madagascar'),
('Cesar', 'Fantham', 'cfantham1p@dion.ne.jp', 'Guintubhan', 'Philippines'),
('Flori', 'Altofts', 'faltofts1q@cloudflare.com', 'Xiaomenjia', 'China'),
('Marta', 'Maccrea', 'mmaccrea1r@chronoengine.com', 'Stari Bar', 'Montenegro'),
('Guglielma', 'Zolini', 'gzolini1s@blogtalkradio.com', 'Hvar', 'Croatia'),
('Sydel', 'O''Kieran', 'sokieran1t@icio.us', 'Sumberpandan', 'Indonesia'),
('Ruthann', 'Mackney', 'rmackney1u@comcast.net', 'Pirot', 'Serbia'),
('Evyn', 'Mc Caughen', 'emccaughen1v@foxnews.com', 'Hecun', 'China'),
('Paulina', 'Feare', 'pfeare1w@amazon.co.jp', 'Compiègne', 'France'),
('Jo', 'Sharram', 'jsharram1x@nymag.com', 'Sepīdān', 'Iran'),
('Walton', 'Peascod', 'wpeascod1y@craigslist.org', 'Boca de Uchire', 'Venezuela'),
('Ollie', 'Cordoba', 'ocordoba1z@cloudflare.com', 'Šardice', 'Czech Republic'),
('Manolo', 'Nicely', 'mnicely20@dedecms.com', 'Palaífyto', 'Greece'),
('Rakel', 'Ownsworth', 'rownsworth21@hao123.com', 'Stoszowice', 'Poland'),
('Averyl', 'Stanlick', 'astanlick22@i2i.jp', 'Caldas da Felgueira', 'Portugal'),
('Yehudi', 'Garrold', 'ygarrold23@privacy.gov.au', 'Guizi', 'China'),
('Eddy', 'Ralton', 'eralton24@guardian.co.uk', 'Shypyntsi', 'Ukraine'),
('Angil', 'Eilers', 'aeilers25@huffingtonpost.com', 'Amman', 'Jordan'),
('Sadye', 'Sodo', 'ssodo26@newsvine.com', 'Ipoh', 'Malaysia'),
('Laverna', 'O''Kennedy', 'lokennedy27@dmoz.org', 'Zhamao', 'China'),
('Livvy', 'Keatch', 'lkeatch28@npr.org', 'Skara', 'Sweden'),
('Debi', 'Littlefair', 'dlittlefair29@trellian.com', 'Dargaz', 'Iran'),
('Ermina', 'Karlowicz', 'ekarlowicz2a@ucsd.edu', 'Le Mans', 'France'),
('Gwennie', 'Mitchiner', 'gmitchiner2b@sphinn.com', 'Ananindeua', 'Brazil'),
('Wanda', 'Neylon', 'wneylon2c@exblog.jp', 'Al Fayyūm', 'Egypt'),
('Cassondra', 'Habbeshaw', 'chabbeshaw2d@yellowbook.com', 'Baishi', 'China'),
('Lynde', 'Wivell', 'lwivell2e@buzzfeed.com', 'Zhijiang', 'China'),
('Patrizius', 'Probet', 'pprobet2f@sbwire.com', 'Wan Yai', 'Thailand'),
('Fons', 'Schneidau', 'fschneidau2g@dot.gov', 'Angan', 'Indonesia'),
('Sindee', 'Crowthe', 'scrowthe2h@drupal.org', 'San Vicente', 'Chile'),
('Christie', 'McIlheran', 'cmcilheran2i@utexas.edu', 'Luena', 'Angola'),
('Allie', 'Farbrother', 'afarbrother2j@shop-pro.jp', 'Kalianda', 'Indonesia'),
('Talbot', 'Elion', 'telion2k@vk.com', 'Sabanitas', 'Panama'),
('Bel', 'Pfeffel', 'bpfeffel2l@netvibes.com', 'Ostankinskiy', 'Russia'),
('Aidan', 'Sheeres', 'asheeres2m@skype.com', 'Ratnapura', 'Sri Lanka'),
('Torrin', 'Gabey', 'tgabey2n@sina.com.cn', 'Bao’an', 'China'),
('Doy', 'McQuilkin', 'dmcquilkin2o@gnu.org', 'Tielu', 'China'),
('Joseito', 'Coltart', 'jcoltart2p@harvard.edu', 'Khon San', 'Thailand'),
('Keelia', 'Van der Spohr', 'kvanderspohr2q@uiuc.edu', 'Gedongmulyo', 'Indonesia'),
('Jere', 'Meeny', 'jmeeny2r@ezinearticles.com', 'Turinsk', 'Russia'),
('Minta', 'Stannislawski', 'mstannislawski2s@sohu.com', 'Skarbimierz Osiedle', 'Poland'),
('Tim', 'Michiel', 'tmichiel2t@ucoz.ru', 'Daping', 'China'),
('Daphene', 'Rebbeck', 'drebbeck2u@theatlantic.com', 'Caminaca', 'Peru'),
('Myrlene', 'Whitmore', 'mwhitmore2v@cloudflare.com', 'Kopashnovo', 'Ukraine'),
('Kerby', 'McArthur', 'kmcarthur2w@aol.com', 'Valence', 'France'),
('Sephira', 'Instrell', 'sinstrell2x@pinterest.com', 'Perivólia', 'Cyprus'),
('Jean', 'Grier', 'jgrier2y@a8.net', 'Popovo', 'Russia'),
('Fayre', 'LAbbet', 'flabbet2z@google.fr', 'Lobuk', 'Indonesia'),
('Nelson', 'Sreenan', 'nsreenan30@harvard.edu', 'Charlotte', 'United States'),
('Gail', 'Tonner', 'gtonner31@admin.ch', 'Chixi', 'China'),
('Nil', 'Dachey', 'ndachey32@rakuten.co.jp', 'Bradashesh', 'Albania'),
('Neale', 'Goodban', 'ngoodban33@mayoclinic.com', 'Yangkang', 'China'),
('Efrem', 'Eykelbosch', 'eeykelbosch34@shareasale.com', 'Iwata', 'Japan'),
('Hatty', 'Hatchette', 'hhatchette35@ovh.net', 'Heqiao', 'China'),
('Lazar', 'Clark', 'lclark36@foxnews.com', 'Ungus-Ungus', 'Philippines'),
('Kristian', 'Knowlman', 'kknowlman37@fda.gov', 'San Jose', 'Philippines'),
('Hedvige', 'Rottenbury', 'hrottenbury38@tinypic.com', 'Huangtu', 'China'),
('Oralla', 'Simmank', 'osimmank39@tiny.cc', 'Saintes', 'France'),
('Felizio', 'Creedland', 'fcreedland3a@opensource.org', 'Kunwi', 'South Korea'),
('Danya', 'Kuhnert', 'dkuhnert3b@desdev.cn', 'Jasień', 'Poland'),
('Delphine', 'Laite', 'dlaite3c@reference.com', 'Miyata', 'Japan'),
('Mala', 'Tindle', 'mtindle3d@squidoo.com', 'Dem’yanovo', 'Russia'),
('Lindy', 'Moreing', 'lmoreing3e@amazon.com', 'Bago', 'Indonesia'),
('Dylan', 'Boater', 'dboater3f@psu.edu', 'Falënki', 'Russia'),
('Clint', 'Tunmore', 'ctunmore3g@printfriendly.com', 'Opochka', 'Russia'),
('Jeth', 'Lomen', 'jlomen3h@google.com.hk', 'Xubao', 'China'),
('Catherine', 'Dwight', 'cdwight3i@comcast.net', 'Taha Man Zu', 'China'),
('Ethyl', 'Layson', 'elayson3j@myspace.com', 'Manay', 'Philippines'),
('Wren', 'Seson', 'wseson3k@reddit.com', 'Sztum', 'Poland'),
('Karla', 'Morley', 'kmorley3l@sitemeter.com', 'Az Zabadānī', 'Syria'),
('Petrina', 'Lacotte', 'placotte3m@sina.com.cn', 'Couto', 'Portugal'),
('Willabella', 'Wellbeloved', 'wwellbeloved3n@baidu.com', 'Myasnikyan', 'Armenia'),
('Simmonds', 'Praundlin', 'spraundlin3o@columbia.edu', 'Heshengbao', 'China'),
('Meagan', 'Normandale', 'mnormandale3p@sakura.ne.jp', 'Saint-Paul', 'Reunion'),
('Moyra', 'Bartol', 'mbartol3q@hatena.ne.jp', 'Bajingmeduro', 'Indonesia'),
('Gaile', 'Clem', 'gclem3r@go.com', 'Yabrūd', 'Syria'),
('Shawna', 'Losano', 'slosano3s@businessinsider.com', 'Sennoy', 'Russia'),
('Avril', 'Rack', 'arack3t@cam.ac.uk', 'Thị Trấn Tam Sơn', 'Vietnam'),
('Elia', 'Enderwick', 'eenderwick3u@forbes.com', 'Aykhal', 'Russia'),
('Rob', 'Limrick', 'rlimrick3v@cam.ac.uk', 'Kapunduk', 'Indonesia'),
('Anastasie', 'Ingram', 'aingram3w@shinystat.com', 'Działdowo', 'Poland'),
('Abigail', 'Breeze', 'abreeze3x@washingtonpost.com', 'Pylaía', 'Greece'),
('Marga', 'Goodinson', 'mgoodinson3y@mysql.com', 'Leuwidamar', 'Indonesia'),
('Loise', 'Hallsworth', 'lhallsworth3z@hhs.gov', 'Gongnong', 'China'),
('Sella', 'Zavattari', 'szavattari40@macromedia.com', 'Limoges', 'France'),
('Darin', 'Cope', 'dcope41@patch.com', 'Maurole', 'Indonesia'),
('Renard', 'Sutterby', 'rsutterby42@desdev.cn', 'Goba', 'Ethiopia'),
('Myrah', 'Waters', 'mwaters43@deliciousdays.com', 'Täby', 'Sweden'),
('Max', 'Screas', 'mscreas44@fc2.com', 'Przodkowo', 'Poland'),
('Pren', 'Rizzetti', 'prizzetti45@infoseek.co.jp', 'Tianyu', 'China'),
('Dorelle', 'Bolam', 'dbolam46@paypal.com', 'Diré', 'Mali'),
('Normy', 'Sallows', 'nsallows47@answers.com', 'Znamenskoye', 'Russia'),
('Kippar', 'Zamora', 'kzamora48@arizona.edu', 'Presidente Venceslau', 'Brazil'),
('Bert', 'Howsin', 'bhowsin49@reverbnation.com', 'Bruxelles', 'Belgium'),
('Flo', 'Lefeaver', 'flefeaver4a@nymag.com', 'Alqueva', 'Portugal'),
('Barn', 'Eastam', 'beastam4b@pcworld.com', 'Zborovice', 'Czech Republic'),
('Tallie', 'Middas', 'tmiddas4c@amazon.co.jp', 'Salerno', 'Italy'),
('Kaiser', 'Pech', 'kpech4d@symantec.com', 'Mangseng', 'Indonesia'),
('Joby', 'D''Aeth', 'jdaeth4e@angelfire.com', 'Nahrīn', 'Afghanistan'),
('Wood', 'Ciric', 'wciric4f@meetup.com', 'Horta', 'Portugal'),
('Katheryn', 'Chung', 'kchung4g@paypal.com', 'Xike', 'China'),
('Pepillo', 'Luna', 'pluna4h@ifeng.com', 'Koroška Bela', 'Slovenia'),
('Ardis', 'Odams', 'aodams4i@mozilla.org', 'Vermoim', 'Portugal'),
('Nealson', 'Marmion', 'nmarmion4j@nhs.uk', 'Kronshtadt', 'Russia'),
('Ellswerth', 'Allworthy', 'eallworthy4k@youtu.be', 'Zehak', 'Iran'),
('Homerus', 'Pottage', 'hpottage4l@odnoklassniki.ru', 'Kobylanka', 'Poland'),
('Sayers', 'McCulley', 'smcculley4m@bloglines.com', 'Pedro Miguel', 'Portugal'),
('Drud', 'Swains', 'dswains4n@scribd.com', 'Gondar', 'Ethiopia'),
('Wait', 'Broomer', 'wbroomer4o@google.co.jp', 'Chantilly', 'France'),
('Beaufort', 'Huzzey', 'bhuzzey4p@yale.edu', 'Sumbuya', 'Sierra Leone'),
('Kimberly', 'Bignold', 'kbignold4q@smh.com.au', 'Zátor', 'Czech Republic'),
('Liva', 'Kevane', 'lkevane4r@multiply.com', 'Machetá', 'Colombia'),
('Robinet', 'Ebhardt', 'rebhardt4s@ning.com', 'Tomar', 'Portugal'),
('Norene', 'Snipe', 'nsnipe4t@gmpg.org', 'Tours', 'France'),
('Gert', 'Tarbin', 'gtarbin4u@skype.com', 'Yurkivka', 'Ukraine'),
('Tiffany', 'Hartington', 'thartington4v@microsoft.com', 'Malbork', 'Poland'),
('Codie', 'De Meyer', 'cdemeyer4w@scribd.com', 'Metsemotlhaba', 'Botswana'),
('Delcine', 'Baughan', 'dbaughan4x@live.com', 'Soho', 'Indonesia'),
('Evaleen', 'Kleszinski', 'ekleszinski4y@storify.com', 'Triandría', 'Greece'),
('Jud', 'Whitley', 'jwhitley4z@posterous.com', 'Jelcz', 'Poland'),
('Early', 'Waith', 'ewaith50@people.com.cn', 'Lima Pampa', 'Peru'),
('Viviene', 'Layburn', 'vlayburn51@storify.com', 'Huangjia', 'China'),
('Jana', 'Klazenga', 'jklazenga52@cpanel.net', 'Alderetes', 'Argentina'),
('Salvador', 'Lambdon', 'slambdon53@sfgate.com', 'Morfovoúni', 'Greece'),
('Pincus', 'Ranklin', 'pranklin54@w3.org', 'Volokolamsk', 'Russia'),
('Tonya', 'Adger', 'tadger55@histats.com', 'Nantes', 'France'),
('Rip', 'Iorizzo', 'riorizzo56@google.nl', 'Mpigi', 'Uganda'),
('Nicolea', 'Venning', 'nvenning57@redcross.org', 'Syrostan', 'Russia'),
('Torie', 'Labbati', 'tlabbati58@imdb.com', 'Vovchans’k', 'Ukraine'),
('Ayn', 'Murrells', 'amurrells59@dropbox.com', 'Rundeng', 'Indonesia'),
('Ilsa', 'Fisbey', 'ifisbey5a@va.gov', 'Poponcol', 'Indonesia'),
('Grannie', 'Jahnke', 'gjahnke5b@hostgator.com', 'Salvacion', 'Philippines'),
('Nester', 'Robillard', 'nrobillard5c@adobe.com', 'San Diego', 'Philippines'),
('Felecia', 'Hoggins', 'fhoggins5d@bbc.co.uk', 'Baoshui', 'China'),
('Bonita', 'Ruby', 'bruby5e@ca.gov', 'Kwangju', 'South Korea'),
('Cornie', 'Tyer', 'ctyer5f@intel.com', 'Vidzy', 'Belarus'),
('Glen', 'Hagart', 'ghagart5g@seattletimes.com', 'Prior Velho', 'Portugal'),
('Bevan', 'Ganders', 'bganders5h@shinystat.com', 'Barra do Bugres', 'Brazil'),
('Corine', 'Lisett', 'clisett5i@t-online.de', 'Dahedian', 'China'),
('Olly', 'Sailor', 'osailor5j@ebay.co.uk', 'Tarogong', 'Indonesia'),
('Selene', 'Hadgraft', 'shadgraft5k@redcross.org', 'Guarabira', 'Brazil'),
('Bernadene', 'Martinon', 'bmartinon5l@geocities.jp', 'Almere Stad', 'Netherlands'),
('Gerardo', 'Mellsop', 'gmellsop5m@so-net.ne.jp', 'Fangyan', 'China'),
('Jeffy', 'Sandwick', 'jsandwick5n@statcounter.com', 'Riachão do Jacuípe', 'Brazil'),
('Kori', 'Benterman', 'kbenterman5o@jiathis.com', 'Vel’sk', 'Russia'),
('Nathalia', 'Drioli', 'ndrioli5p@1688.com', 'Independencia', 'Mexico'),
('Hyacinthia', 'Gouda', 'hgouda5q@patch.com', 'Pingfeng', 'China'),
('Alyson', 'Piggott', 'apiggott5r@mayoclinic.com', 'Ryjewo', 'Poland'),
('Diego', 'Islip', 'dislip5s@about.me', 'Pshada', 'Russia'),
('Doyle', 'Maffey', 'dmaffey5t@google.pl', 'Puncaksempur', 'Indonesia'),
('Frances', 'Ruppel', 'fruppel5u@altervista.org', 'Dubrovka', 'Russia'),
('Vassili', 'Neilson', 'vneilson5v@digg.com', 'Har-Us', 'Mongolia'),
('Greta', 'Trenbay', 'gtrenbay5w@live.com', 'Uticyacu', 'Peru'),
('Caresa', 'Ladbrook', 'cladbrook5x@spotify.com', 'Lloque', 'Peru'),
('Jobey', 'Retallick', 'jretallick5y@oaic.gov.au', 'Smithers', 'Canada'),
('Erna', 'McKeney', 'emckeney5z@latimes.com', 'Skärholmen', 'Sweden'),
('Kathrine', 'Render', 'krender60@omniture.com', 'Cool űrhajó', 'Afghanistan'),
('Cobby', 'Laddle', 'claddle61@mail.ru', 'Arani', 'Bolivia'),
('Crysta', 'Challender', 'cchallender62@com.com', 'Buena Vista', 'Bolivia'),
('Lemmie', 'Philler', 'lphiller63@europa.eu', 'Videm pri Ptuju', 'Slovenia'),
('Consalve', 'Greaves', 'cgreaves64@yahoo.co.jp', 'Novotitarovskaya', 'Russia'),
('Chucho', 'Anslow', 'canslow65@yahoo.co.jp', 'Komorów', 'Poland'),
('Ogden', 'Smorthit', 'osmorthit66@hibu.com', 'Rumelange', 'Luxembourg'),
('Melania', 'Fines', 'mfines67@dailymotion.com', 'Dukuhpicung', 'Indonesia'),
('Jorry', 'Goodrick', 'jgoodrick68@webeden.co.uk', 'Tegaldowo', 'Indonesia'),
('Adelheid', 'O''Reilly', 'aoreilly69@tuttocitta.it', 'Youkounkoun', 'Guinea'),
('Heall', 'Morgen', 'hmorgen6a@latimes.com', 'Teplice', 'Czech Republic'),
('Arluene', 'Payton', 'apayton6b@utexas.edu', 'Krzyżowice', 'Poland'),
('Britney', 'Ridger', 'bridger6c@goodreads.com', 'Visoko', 'Bosnia and Herzegovina'),
('Sascha', 'Lancastle', 'slancastle6d@addthis.com', 'Salinungan Proper', 'Philippines'),
('Laurice', 'Gorry', 'lgorry6e@studiopress.com', 'Abaeté', 'Brazil'),
('Poul', 'Beamish', 'pbeamish6f@admin.ch', 'Xincheng', 'China'),
('Audre', 'Forsdicke', 'aforsdicke6g@wikispaces.com', 'Barras', 'Brazil'),
('Hamilton', 'Easson', 'heasson6h@hubpages.com', 'Zhuangta', 'China'),
('Monti', 'Korting', 'mkorting6i@google.it', 'Viso', 'Portugal'),
('Celie', 'Stoyles', 'cstoyles6j@answers.com', 'Allacapan', 'Philippines'),
('Vachel', 'Iverson', 'viverson6k@baidu.com', 'Kokologo', 'Burkina Faso'),
('Riki', 'Biset', 'rbiset6l@rediff.com', 'Gandra', 'Portugal'),
('Devi', 'Haggleton', 'dhaggleton6m@sun.com', 'Khujirt', 'Mongolia'),
('Cole', 'Fruchter', 'cfruchter6n@google.pl', 'Kamogatachō-kamogata', 'Japan'),
('Cyb', 'Rubinsky', 'crubinsky6o@theatlantic.com', 'Skomlin', 'Poland'),
('Isac', 'Presman', 'ipresman6p@purevolume.com', 'Elbasan', 'Albania'),
('Stepha', 'Sapena', 'ssapena6q@google.fr', 'Boshkengash', 'Tajikistan'),
('Ignazio', 'Barajas', 'ibarajas6r@netscape.com', 'Rancaseneng', 'Indonesia'),
('Leticia', 'Burdass', 'lburdass6s@soup.io', 'Elektrėnai', 'Lithuania'),
('Cherilyn', 'Garralts', 'cgarralts6t@si.edu', 'Bitobe', 'Indonesia'),
('Gena', 'Hinstock', 'ghinstock6u@example.com', 'Changchuan', 'China'),
('Abbie', 'Imm', 'aimm6v@furl.net', 'Kedunglo', 'Indonesia'),
('Miller', 'Guswell', 'mguswell6w@discovery.com', 'Fengjiang', 'China'),
('Gawen', 'Sansbury', 'gsansbury6x@jalbum.net', 'Maceda', 'Portugal'),
('Gaylene', 'Mulkerrins', 'gmulkerrins6y@hud.gov', 'Kamenka', 'Russia'),
('Gaynor', 'Anker', 'ganker6z@google.es', 'Tulu Bolo', 'Ethiopia'),
('Alissa', 'MacAulay', 'amacaulay70@marketwatch.com', 'Ol’gino', 'Russia'),
('West', 'Doyley', 'wdoyley71@slate.com', 'Pedregulho', 'Brazil'),
('Quinn', 'Zorzetti', 'qzorzetti72@msn.com', 'Lin’an', 'China'),
('Thelma', 'Linder', 'tlinder73@biglobe.ne.jp', 'Pameungpeuk', 'Indonesia'),
('Boot', 'Vitet', 'bvitet74@mapy.cz', 'Rafael Hernandez Ochoa', 'Mexico'),
('Paulita', 'Fallow', 'pfallow75@feedburner.com', 'Issia', 'Ivory Coast'),
('Enid', 'Casone', 'ecasone76@ucoz.com', 'Hujiaba', 'China'),
('Lita', 'Timmermann', 'ltimmermann77@chron.com', 'Washington', 'United States'),
('Foster', 'MacRannell', 'fmacrannell78@forbes.com', 'Shuanggang', 'China'),
('Hamlin', 'Applegarth', 'happlegarth79@wikipedia.org', 'Qingtang', 'China'),
('Ara', 'Klimentyonok', 'aklimentyonok7a@jimdo.com', 'Caibarién', 'Cuba'),
('Fabiano', 'Bewlie', 'fbewlie7b@tripadvisor.com', 'Colca', 'Peru'),
('Morgen', 'Haycroft', 'mhaycroft7c@indiatimes.com', 'Jiangxiangzhen', 'China'),
('Ardith', 'Elcomb', 'aelcomb7d@yolasite.com', 'Copa', 'Peru'),
('Karrie', 'Maytom', 'kmaytom7e@linkedin.com', 'Rossosh’', 'Russia'),
('Beverie', 'Di Boldi', 'bdiboldi7f@mayoclinic.com', 'Deranitan', 'Indonesia'),
('Briana', 'Colston', 'bcolston7g@google.com.au', 'Chajarí', 'Argentina'),
('Billy', 'Pitceathly', 'bpitceathly7h@google.fr', 'Seremban', 'Malaysia'),
('Krystle', 'Balint', 'kbalint7i@wikia.com', 'Ketanggi', 'Indonesia'),
('Sandra', 'Perl', 'sperl7j@spiegel.de', 'San Casimiro', 'Venezuela'),
('Gregoor', 'Melby', 'gmelby7k@sun.com', 'Niigata-shi', 'Japan'),
('Grove', 'Deaton', 'gdeaton7l@ted.com', 'Pärnu', 'Estonia'),
('Jonathan', 'Scoggins', 'jscoggins7m@ebay.co.uk', 'Kaum Kaler', 'Indonesia'),
('Dagmar', 'Higgan', 'dhiggan7n@wikia.com', 'Skeldon', 'Guyana'),
('Rosette', 'Ilsley', 'rilsley7o@harvard.edu', 'Wonosobo', 'Indonesia'),
('Bronson', 'Randle', 'brandle7p@php.net', 'Suvorov', 'Russia'),
('Davis', 'Deeley', 'ddeeley7q@slate.com', 'Davyd-Haradok', 'Belarus'),
('Kerianne', 'Bercher', 'kbercher7r@so-net.ne.jp', 'Lityn', 'Ukraine'),
('Sansone', 'Hightown', 'shightown7s@boston.com', 'Nové Sedlo', 'Czech Republic'),
('Arlie', 'Tabart', 'atabart7t@unicef.org', 'Goulmima', 'Morocco'),
('Julia', 'Loude', 'jloude7u@odnoklassniki.ru', 'Bologoye', 'Russia'),
('Eben', 'Goakes', 'egoakes7v@cmu.edu', 'Hongyi', 'China'),
('Khalil', 'Harsant', 'kharsant7w@a8.net', 'Yaroslavskiy', 'Russia'),
('Jim', 'Pointin', 'jpointin7x@msn.com', 'Karangmulyo', 'Indonesia'),
('Marris', 'Camin', 'mcamin7y@senate.gov', 'Nantes', 'France'),
('Leopold', 'Sedgemond', 'lsedgemond7z@columbia.edu', 'San Borja', 'Bolivia'),
('Boycey', 'Ablett', 'bablett80@yelp.com', 'Quxi', 'China'),
('Querida', 'Jerzykiewicz', 'qjerzykiewicz81@vk.com', 'Nong Ki', 'Thailand'),
('Florette', 'Fessions', 'ffessions82@harvard.edu', 'Bodzechów', 'Poland'),
('Shanan', 'Rubes', 'srubes83@deliciousdays.com', 'Sokolac', 'Bosnia and Herzegovina'),
('Jacquelynn', 'Gravestone', 'jgravestone84@hatena.ne.jp', 'Paraty', 'Brazil'),
('Allsun', 'Olsson', 'aolsson85@tinyurl.com', 'Mangarine', 'Philippines'),
('Pansie', 'Sharnock', 'psharnock86@quantcast.com', 'Kowang Utara', 'Indonesia'),
('Constantia', 'Vallack', 'cvallack87@hao123.com', 'Persen', 'Indonesia'),
('Emlyn', 'Meere', 'emeere88@nps.gov', 'Pskov', 'Russia'),
('Shaylah', 'Brogi', 'sbrogi89@yellowpages.com', 'Laško', 'Slovenia'),
('Tarrance', 'L''Episcopi', 'tlepiscopi8a@ucoz.ru', 'Cikulina', 'Indonesia'),
('Lorry', 'Doerffer', 'ldoerffer8b@fda.gov', 'Krajan Sumurtawang', 'Indonesia'),
('Zarah', 'Waghorn', 'zwaghorn8c@wikimedia.org', 'Pocrí', 'Panama'),
('Leah', 'De Anesy', 'ldeanesy8d@infoseek.co.jp', 'Sambilawang', 'Indonesia'),
('Baxter', 'Castanone', 'bcastanone8e@nifty.com', 'Sighnaghi', 'Georgia'),
('Jeni', 'Wrassell', 'jwrassell8f@apache.org', 'Pantanal', 'Brazil'),
('Wittie', 'Pendre', 'wpendre8g@umn.edu', 'Lanxi', 'China'),
('Jeno', 'Gadeaux', 'jgadeaux8h@omniture.com', 'Pasirangin Tiga', 'Indonesia'),
('Delano', 'Furlonge', 'dfurlonge8i@fotki.com', 'Moss', 'Norway'),
('Sybil', 'Kineton', 'skineton8j@soundcloud.com', 'Wenbi', 'China'),
('Catherina', 'Dressell', 'cdressell8k@edublogs.org', 'Mujur Satu', 'Indonesia'),
('Anissa', 'Ledur', 'aledur8l@cpanel.net', 'The Valley', 'Anguilla'),
('Sheeree', 'Miere', 'smiere8m@accuweather.com', 'María la Baja', 'Colombia'),
('Fannie', 'Pogson', 'fpogson8n@google.fr', 'Bagok', 'Indonesia'),
('Evy', 'Bardwall', 'ebardwall8o@last.fm', 'Timeng', 'China'),
('Dorie', 'Pendleton', 'dpendleton8p@vkontakte.ru', 'Shiqiao', 'China'),
('Trude', 'Millgate', 'tmillgate8q@1und1.de', 'Sigaozhuang', 'China'),
('Kelbee', 'Rabley', 'krabley8r@google.de', 'Tampa', 'United States'),
('Robby', 'Dunmore', 'rdunmore8s@harvard.edu', 'Murtajih', 'Indonesia'),
('Micky', 'Ghidini', 'mghidini8t@homestead.com', 'Nunleu', 'Indonesia'),
('Victoir', 'Dummer', 'vdummer8u@etsy.com', 'Jām Sāhib', 'Pakistan'),
('Cody', 'McArdell', 'cmcardell8v@fotki.com', 'Al Lagowa', 'Sudan'),
('Aaron', 'Riddall', 'ariddall8w@themeforest.net', 'Oranmore', 'Ireland'),
('Tam', 'Benneyworth', 'tbenneyworth8x@upenn.edu', 'Persen', 'Indonesia'),
('Dominga', 'Torricina', 'dtorricina8y@google.es', 'Tornio', 'Finland'),
('Franklyn', 'Peele', 'fpeele8z@ca.gov', 'Dasuhe', 'China'),
('Susanetta', 'Annets', 'sannets90@apache.org', 'Milevsko', 'Czech Republic'),
('Alf', 'Farthin', 'afarthin91@engadget.com', 'Dalupirip', 'Philippines'),
('Kathrine', 'Schmuhl', 'kschmuhl92@timesonline.co.uk', 'Tocota', 'Peru'),
('Thia', 'Rutter', 'trutter93@paypal.com', 'As Salţ', 'Jordan'),
('Fawnia', 'Gontier', 'fgontier94@unicef.org', 'Caringin', 'Indonesia'),
('Howard', 'Peye', 'hpeye95@goodreads.com', 'Yaring', 'Thailand'),
('Miles', 'Bozward', 'mbozward96@seattletimes.com', 'Sawin', 'Poland'),
('Clarie', 'Gocher', 'cgocher97@usa.gov', 'Palmeira', 'Brazil'),
('Donella', 'Blasing', 'dblasing98@google.co.uk', 'Sangat', 'Philippines'),
('Haley', 'Cardoo', 'hcardoo99@last.fm', 'Nagrak', 'Indonesia'),
('Dottie', 'Thewles', 'dthewles9a@sphinn.com', 'Longwantun', 'China'),
('Rice', 'Heatly', 'rheatly9b@a8.net', 'Rennes', 'France'),
('Cleo', 'Prescott', 'cprescott9c@last.fm', 'Guanghou', 'China'),
('Monique', 'Freckingham', 'mfreckingham9d@auda.org.au', 'Luchenza', 'Malawi'),
('Colette', 'Burhill', 'cburhill9e@i2i.jp', 'Changxuanling', 'China'),
('Rey', 'Snibson', 'rsnibson9f@myspace.com', 'Granada', 'Philippines'),
('Miriam', 'Leipoldt', 'mleipoldt9g@geocities.com', 'Pulau Pinang', 'Malaysia'),
('Shaine', 'Chown', 'schown9h@studiopress.com', 'Timbulsari', 'Indonesia'),
('Bil', 'Lindley', 'blindley9i@webmd.com', 'Kampungbaru', 'Indonesia'),
('Tanney', 'Flewin', 'tflewin9j@webeden.co.uk', 'La Concepción', 'Nicaragua'),
('Alleen', 'Apedaile', 'aapedaile9k@hp.com', 'Puerto Asís', 'Colombia'),
('Rodrigo', 'Stendall', 'rstendall9l@cargocollective.com', 'Kotabunan', 'Indonesia'),
('Heinrick', 'Dalgleish', 'hdalgleish9m@smh.com.au', 'Kitahiroshima', 'Japan'),
('Thibaut', 'Schultz', 'tschultz9n@1und1.de', 'Huanshan', 'China'),
('Corie', 'McGriffin', 'cmcgriffin9o@shareasale.com', 'Melíki', 'Greece'),
('Eugine', 'Caddie', 'ecaddie9p@technorati.com', 'Barreiras', 'Portugal'),
('Mela', 'Blowers', 'mblowers9q@state.tx.us', 'Hūn', 'Libya'),
('Rubetta', 'Iveans', 'riveans9r@addtoany.com', 'Jevišovice', 'Czech Republic'),
('Karena', 'Dryden', 'kdryden9s@naver.com', 'Zhongshan Donglu', 'China'),
('Thorvald', 'Titterton', 'ttitterton9t@artisteer.com', 'Widorokandang', 'Indonesia'),
('Celestine', 'Couch', 'ccouch9u@washingtonpost.com', 'Pasrūr', 'Pakistan'),
('Marietta', 'Pandya', 'mpandya9v@ifeng.com', 'Kaliuda', 'Indonesia'),
('Andi', 'Jeannequin', 'ajeannequin9w@nifty.com', 'Kista', 'Sweden'),
('Katti', 'Piwall', 'kpiwall9x@auda.org.au', 'Bilaran', 'Philippines'),
('Basil', 'Harflete', 'bharflete9y@naver.com', 'Lañgub', 'Philippines'),
('Maxie', 'Jasik', 'mjasik9z@opensource.org', 'Glinojeck', 'Poland'),
('Annalee', 'Tilbury', 'atilburya0@npr.org', 'Nart', 'Mongolia'),
('Francklyn', 'Izzett', 'fizzetta1@typepad.com', 'Fonte da Aldeia', 'Portugal'),
('Bernetta', 'Thorald', 'bthoralda2@amazon.co.jp', 'Íquira', 'Colombia'),
('Candy', 'Child', 'cchilda3@pcworld.com', 'Frampol', 'Poland'),
('Jens', 'Lebourn', 'jlebourna4@t-online.de', 'Ribeiro', 'Portugal'),
('Jerrie', 'Deamer', 'jdeamera5@alibaba.com', 'Lafayette', 'United States'),
('Torre', 'Shrimpling', 'tshrimplinga6@nhs.uk', 'San Vicente', 'Philippines'),
('Benedict', 'Tomenson', 'btomensona7@creativecommons.org', 'Genyem', 'Indonesia'),
('Tiffanie', 'Ennew', 'tennewa8@parallels.com', 'Tsukumiura', 'Japan'),
('Johannes', 'Filov', 'jfilova9@newyorker.com', 'Oemollo', 'Indonesia'),
('Kathy', 'Kopisch', 'kkopischaa@wired.com', 'Rowokangkung', 'Indonesia'),
('Lemmie', 'Quinney', 'lquinneyab@alibaba.com', 'Bejsce', 'Poland'),
('Bord', 'Hessel', 'bhesselac@loc.gov', 'Rameshki', 'Russia'),
('Godfrey', 'Phipson', 'gphipsonad@ovh.net', 'Bacag', 'Philippines'),
('Francklin', 'Mosen', 'fmosenae@spiegel.de', 'Moulay Bouchta', 'Morocco'),
('Euell', 'Grgic', 'egrgicaf@google.com.hk', 'Jiahe', 'China'),
('Andrei', 'Brideoke', 'abrideokeag@boston.com', 'Sopo', 'Indonesia'),
('Madella', 'Witchard', 'mwitchardah@scientificamerican.com', 'Lapuan', 'Philippines'),
('Belia', 'Setchfield', 'bsetchfieldai@wp.com', 'Jablunkov', 'Czech Republic'),
('Leola', 'Sparrowhawk', 'lsparrowhawkaj@netlog.com', 'Xingquan', 'China'),
('Steward', 'Maughan', 'smaughanak@discovery.com', 'Serowe', 'Botswana'),
('Conroy', 'Koppeck', 'ckoppeckal@wordpress.org', 'Calasgasan', 'Philippines'),
('Harrie', 'Gladdolph', 'hgladdolpham@pagesperso-orange.fr', 'Catalão', 'Brazil'),
('Martie', 'Gartery', 'mgarteryan@etsy.com', 'Hailin', 'China'),
('Gratiana', 'Mackinder', 'gmackinderao@java.com', 'Pung-Pang', 'Philippines'),
('Ramsay', 'Gabbett', 'rgabbettap@ask.com', 'Jiling', 'China'),
('Sharron', 'Rosenbush', 'srosenbushaq@sun.com', 'Abomey-Calavi', 'Benin'),
('Valaria', 'Kiledal', 'vkiledalar@eventbrite.com', 'Staryy Oskol', 'Russia'),
('Marnie', 'Fullun', 'mfullunas@tripadvisor.com', 'Alto Río Senguer', 'Argentina'),
('Isador', 'Hards', 'ihardsat@hostgator.com', 'Thaton', 'Myanmar'),
('Fidel', 'Ismead', 'fismeadau@google.pl', 'Zhulan', 'China'),
('Roanna', 'Fewlass', 'rfewlassav@a8.net', 'Al Kiswah', 'Syria'),
('Sherman', 'Eppson', 'seppsonaw@boston.com', 'Dalun', 'China'),
('Mavra', 'Voase', 'mvoaseax@twitpic.com', 'Xinan', 'China'),
('Rodge', 'Armiger', 'rarmigeray@noaa.gov', 'São Martinho de Árvore', 'Portugal'),
('Alfie', 'Duckering', 'aduckeringaz@ow.ly', 'Vinica', 'Macedonia'),
('Brianna', 'Hyndes', 'bhyndesb0@salon.com', 'Guxian', 'China'),
('Adrianna', 'Vlasyev', 'avlasyevb1@over-blog.com', 'Kýthnos', 'Greece'),
('Jaquelyn', 'Southard', 'jsouthardb2@goodreads.com', 'Xinglong', 'China'),
('Halimeda', 'Crathern', 'hcrathernb3@netscape.com', 'Beilun', 'China'),
('Sylvester', 'Chansonne', 'schansonneb4@facebook.com', 'Lapachito', 'Argentina'),
('Sidoney', 'Elvey', 'selveyb5@sina.com.cn', 'Qiaotou', 'China'),
('Victor', 'MacKartan', 'vmackartanb6@tinypic.com', 'Peicheng', 'China'),
('Heida', 'Vannet', 'hvannetb7@latimes.com', 'Onzaga', 'Colombia'),
('Bertram', 'Huffa', 'bhuffab8@rakuten.co.jp', 'Paseyan', 'Indonesia'),
('Max', 'Grunnell', 'mgrunnellb9@ustream.tv', 'Emiliano Zapata', 'Mexico'),
('My', 'Fullager', 'mfullagerba@answers.com', 'Suzëmka', 'Russia'),
('Vere', 'Blumer', 'vblumerbb@economist.com', 'Kaduketug', 'Indonesia'),
('Loy', 'Bailes', 'lbailesbc@dailymail.co.uk', 'Estância Velha', 'Brazil'),
('Pierette', 'Palser', 'ppalserbd@nyu.edu', 'Grimstad', 'Norway'),
('Dwayne', 'Harrod', 'dharrodbe@zdnet.com', 'Albufeira', 'Portugal'),
('Stanford', 'Slany', 'sslanybf@hud.gov', 'Golacir', 'Indonesia'),
('Fancie', 'Shawyer', 'fshawyerbg@house.gov', 'Mashava', 'Zimbabwe'),
('Elset', 'Kelcher', 'ekelcherbh@mtv.com', 'Wilmington', 'United States'),
('Georgianne', 'McCoish', 'gmccoishbi@vimeo.com', 'Phoenix', 'United States'),
('Waiter', 'Dewhurst', 'wdewhurstbj@netvibes.com', 'Gränna', 'Sweden'),
('Ulises', 'Luckcuck', 'uluckcuckbk@cbsnews.com', 'Zhengcun', 'China'),
('Alonso', 'Nockalls', 'anockallsbl@webnode.com', 'Glamang', 'Philippines'),
('Ginger', 'Gwynn', 'ggwynnbm@phpbb.com', 'Bejsce', 'Poland'),
('Josephina', 'Sutcliff', 'jsutcliffbn@is.gd', 'Jefferson City', 'United States'),
('Wilfred', 'Dowse', 'wdowsebo@blog.com', 'Bongao', 'Philippines'),
('Early', 'Abry', 'eabrybp@ebay.com', 'Hongmiao', 'China'),
('Clarita', 'Bourgour', 'cbourgourbq@wiley.com', 'Macedo de Cavaleiros', 'Portugal'),
('Jeremy', 'Vasyunkin', 'jvasyunkinbr@pagesperso-orange.fr', 'Sim', 'Russia'),
('Cyndy', 'Wymer', 'cwymerbs@about.com', 'Libouchec', 'Czech Republic'),
('Klarika', 'Elmes', 'kelmesbt@dmoz.org', 'Thị Trấn Mường Khến', 'Vietnam'),
('Abbey', 'Iorizzo', 'aiorizzobu@gnu.org', 'Dallas', 'United States'),
('Brooke', 'Petyanin', 'bpetyaninbv@phoca.cz', 'Shuangnian', 'China'),
('Lilias', 'Pembery', 'lpemberybw@umich.edu', 'Liudu', 'China'),
('Fielding', 'Abramamovh', 'fabramamovhbx@theatlantic.com', 'Falun', 'Sweden'),
('Celesta', 'Haslehurst', 'chaslehurstby@usa.gov', 'Olyka', 'Ukraine'),
('Fergus', 'Ingrey', 'fingreybz@goo.gl', 'Watublapi', 'Indonesia'),
('Modesta', 'Chagg', 'mchaggc0@icq.com', 'Zagórze', 'Poland'),
('Kaela', 'Dudenie', 'kdudeniec1@cnn.com', 'Columbus', 'United States'),
('Annmaria', 'Rooke', 'arookec2@vkontakte.ru', 'Dalu', 'China'),
('Sayers', 'Hendrickson', 'shendricksonc3@biglobe.ne.jp', 'Quảng Ngãi', 'Vietnam'),
('Gustave', 'Clewes', 'gclewesc4@mtv.com', 'Mangai', 'Democratic Republic of the Congo'),
('Aimee', 'Kalinsky', 'akalinskyc5@mapquest.com', 'Kruengraya', 'Indonesia'),
('Tess', 'Cable', 'tcablec6@zimbio.com', 'Katrineholm', 'Sweden'),
('Kimbra', 'Gaskal', 'kgaskalc7@apple.com', 'Nanqi', 'China'),
('Reggis', 'Keemar', 'rkeemarc8@t.co', 'Fort Lauderdale', 'United States'),
('Leia', 'MacIntosh', 'lmacintoshc9@foxnews.com', 'Wuxia', 'China'),
('Paxon', 'McGiveen', 'pmcgiveenca@sciencedaily.com', 'Oslo', 'Norway'),
('Clarice', 'Crole', 'ccrolecb@seattletimes.com', 'Bocowanti', 'Indonesia'),
('Chaim', 'Otson', 'cotsoncc@ucoz.com', 'Duobao', 'China'),
('Kailey', 'Aronov', 'karonovcd@csmonitor.com', 'Kamenjane', 'Macedonia'),
('Thurston', 'Beldam', 'tbeldamce@arizona.edu', 'Lokolande', 'Indonesia'),
('Davidson', 'Lyddiard', 'dlyddiardcf@parallels.com', 'Leuweheq', 'Indonesia'),
('Jereme', 'Belding', 'jbeldingcg@taobao.com', 'Casal da Anja', 'Portugal'),
('Roby', 'Spink', 'rspinkch@sbwire.com', 'Yandev', 'Nigeria'),
('Ardelis', 'Gercken', 'agerckenci@icq.com', 'Shazhuang', 'China'),
('Belvia', 'Itzig', 'bitzigcj@hp.com', 'Francisco Villa', 'Mexico'),
('Nerte', 'Bonson', 'nbonsonck@latimes.com', 'Fort Wayne', 'United States'),
('Christa', 'St Leger', 'cstlegercl@ucsd.edu', 'Marseille', 'France'),
('Hakeem', 'Gooda', 'hgoodacm@webs.com', 'Leigongmiao', 'China'),
('Dennison', 'Trenholm', 'dtrenholmcn@over-blog.com', 'Flin Flon', 'Canada'),
('Penny', 'Kinge', 'pkingeco@mashable.com', 'São Domingos de Rana', 'Portugal'),
('Carmita', 'Desport', 'cdesportcp@wordpress.com', 'Zhaojia', 'China'),
('Cello', 'Bichener', 'cbichenercq@typepad.com', 'Sotíra', 'Cyprus'),
('Clemens', 'Burden', 'cburdencr@miibeian.gov.cn', 'Przystajń', 'Poland'),
('Sherwood', 'Aleksandrev', 'saleksandrevcs@ox.ac.uk', 'Penamacor', 'Portugal'),
('Talya', 'Boxhall', 'tboxhallct@jugem.jp', 'Bjästa', 'Sweden'),
('Eliot', 'Sylvester', 'esylvestercu@aol.com', 'Baofeng', 'China'),
('Emera', 'Mouncher', 'emounchercv@123-reg.co.uk', 'Sedlice', 'Czech Republic'),
('Elspeth', 'Frie', 'efriecw@chicagotribune.com', 'Rio Brilhante', 'Brazil'),
('Fairfax', 'Bramsen', 'fbramsencx@bravesites.com', 'Shiqiao', 'China'),
('Renee', 'Rolfe', 'rrolfecy@state.gov', 'Kaburon', 'Indonesia'),
('Zsazsa', 'Steynor', 'zsteynorcz@spotify.com', 'Andarapa', 'Peru'),
('Lynne', 'Balazs', 'lbalazsd0@mapy.cz', 'Hongtang', 'China'),
('Crichton', 'Sealey', 'csealeyd1@123-reg.co.uk', 'Lahuaytambo', 'Peru'),
('Rosella', 'Bewshea', 'rbewshead2@dyndns.org', 'Cihambali', 'Indonesia'),
('Rey', 'Hubback', 'rhubbackd3@seesaa.net', 'Kamyshin', 'Russia'),
('Tiertza', 'Bittleson', 'tbittlesond4@domainmarket.com', 'Clogherhead', 'Ireland'),
('Marlee', 'McCrow', 'mmccrowd5@goodreads.com', 'Yangxu', 'China'),
('Celine', 'Weatherhill', 'cweatherhilld6@cpanel.net', 'Honghualiangzi', 'China'),
('Clemmy', 'Renowden', 'crenowdend7@epa.gov', 'Katy', 'United States'),
('Piotr', 'Rebeiro', 'prebeirod8@vk.com', 'Shchelkovo', 'Russia'),
('Mufi', 'Tarquinio', 'mtarquiniod9@php.net', 'Chayek', 'Kyrgyzstan'),
('Tedie', 'Bilsford', 'tbilsfordda@ca.gov', 'Qingshu', 'China'),
('Tore', 'Grise', 'tgrisedb@foxnews.com', 'Las Ánimas', 'Honduras'),
('Calv', 'Dorot', 'cdorotdc@weibo.com', 'Faraulep', 'Micronesia'),
('Nicolle', 'Chaldecott', 'nchaldecottdd@eepurl.com', 'Jezzîne', 'Lebanon'),
('Ralf', 'Tibbles', 'rtibblesde@princeton.edu', 'Bherāmāra', 'Bangladesh'),
('Susana', 'Pickthorne', 'spickthornedf@bluehost.com', 'Marne-la-Vallée', 'France'),
('Susette', 'Limeburn', 'slimeburndg@ed.gov', 'Kendung Timur', 'Indonesia'),
('Carce', 'Sarll', 'csarlldh@smugmug.com', 'Sake', 'Democratic Republic of the Congo'),
('Whitman', 'Bassil', 'wbassildi@networksolutions.com', 'Lahān', 'Nepal'),
('Gaspard', 'Sanpere', 'gsanperedj@pcworld.com', 'Halimpu', 'Indonesia'),
('Madonna', 'Cashman', 'mcashmandk@constantcontact.com', 'Acacías', 'Colombia'),
('Heddie', 'Embleton', 'hembletondl@1und1.de', 'Migues', 'Uruguay'),
('Delcina', 'Dover', 'ddoverdm@meetup.com', 'Rozhniv', 'Ukraine'),
('Laure', 'Enderlein', 'lenderleindn@tamu.edu', 'Angono', 'Philippines'),
('Lindy', 'Makeswell', 'lmakeswelldo@unicef.org', 'Haruai', 'Indonesia'),
('Rudolf', 'Vere', 'rveredp@wunderground.com', 'Yujia’ao', 'China'),
('Helli', 'Iaduccelli', 'hiaduccellidq@gmpg.org', 'Charenton-le-Pont', 'France'),
('Maddie', 'Martland', 'mmartlanddr@google.fr', 'La Motte-Servolex', 'France'),
('Minerva', 'Delacroux', 'mdelacrouxds@weibo.com', 'Bireun', 'Indonesia'),
('Shandeigh', 'Hearst', 'shearstdt@ifeng.com', 'Vila Franca de Xira', 'Portugal'),
('Malvin', 'Aslie', 'masliedu@uiuc.edu', 'Gaimán', 'Argentina'),
('Budd', 'Klimpt', 'bklimptdv@yellowpages.com', 'Thị Trấn Phong Thổ', 'Vietnam');

GENRESALTER TABLE CUSTOMERS
ADD FOREIGN KEY (country_id) REFERENCES LOCATIONS(country_id)