CREATE TABLE LOCATIONS (
	country_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    country_name VARCHAR (50),
    salesRegion VARCHAR (50)
);
## for recreating
DROP TABLE LOCATIONS

TRUNCATE TABLE LOCATIONS

## took out location and region - keeping it simple
ALTER TABLE LOCATIONS
DROP COLUMN region_name
## copied data from cmer table
INSERT INTO LOCATIONS ( country_name)
SELECT country
FROM CUSTOMERS
## removing null values
DELETE FROM LOCATIONS
WHERE
	location_name is NULL;
    
## setting sales regions
UPDATE LOCATIONS
SET salesRegion = "Europe"
WHERE country_name IN ("Albania", "Andorra", "Armenia", "Austria", "Belarus","Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia", "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Latvia", "Liechtenstein", "Lithuania"
"Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Turkey", "Ukraine", "United Kingdom", "Vatican City")


## adding more countries
INSERT INTO LOCATIONS (country_name)
SELECT DISTINCT LOC
FROM ALL_LOCATIONS

select * from locations

## add more regional identifiers
select GROUP_CONCAT(DISTINCT country_name
	ORDER BY country_name ASC
    SEPARATOR ', ')
from locations

## NB. ended up just finding a better table online :)
## ADDING IN ALL COUNTRIES AND CONTINENTAL CODES
ALTER TABLE LOCATIONS
ADD COLUMN country_code VARCHAR (2)

ALTER TABLE CUSTOMERS
DROP CONSTRAINT customers_ibfk_1

TRUNCATE TABLE LOCATIONS

INSERT INTO LOCATIONS
	(country_code, country_name, salesRegion)
VALUES
	('AD', 'Andorra', 'EU'),
	('AE', 'United Arab Emirates', 'AS'),
	('AF', 'Afghanistan', 'AS'),
	('AG', 'Antigua and Barbuda', 'NA'),
	('AI', 'Anguilla', 'NA'),
	('AL', 'Albania', 'EU'),
	('AM', 'Armenia', 'AS'),
	('AN', 'Netherlands Antilles', 'NA'),
	('AO', 'Angola', 'AF'),
	('AQ', 'Antarctica', 'AN'),
	('AR', 'Argentina', 'SA'),
	('AS', 'American Samoa', 'OC'),
	('AT', 'Austria', 'EU'),
	('AU', 'Australia', 'OC'),
	('AW', 'Aruba', 'NA'),
	('AX', 'Åland', 'EU'),
	('AZ', 'Azerbaijan', 'AS'),
	('BA', 'Bosnia and Herzegovina', 'EU'),
	('BB', 'Barbados', 'NA'),
	('BD', 'Bangladesh', 'AS'),
	('BE', 'Belgium', 'EU'),
	('BF', 'Burkina Faso', 'AF'),
	('BG', 'Bulgaria', 'EU'),
	('BH', 'Bahrain', 'AS'),
	('BI', 'Burundi', 'AF'),
	('BJ', 'Benin', 'AF'),
	('BL', 'Saint Barthélemy', 'NA'),
	('BM', 'Bermuda', 'NA'),
	('BN', 'Brunei Darussalam', 'AS'),
	('BO', 'Bolivia', 'SA'),
	('BR', 'Brazil', 'SA'),
	('BS', 'Bahamas', 'NA'),
	('BT', 'Bhutan', 'AS'),
	('BV', 'Bouvet Island', 'AN'),
	('BW', 'Botswana', 'AF'),
	('BY', 'Belarus', 'EU'),
	('BZ', 'Belize', 'NA'),
	('CA', 'Canada', 'NA'),
	('CC', 'Cocos (Keeling) Islands', 'AS'),
	('CD', 'Congo (Kinshasa)', 'AF'),
	('CF', 'Central African Republic', 'AF'),
	('CG', 'Congo (Brazzaville)', 'AF'),
	('CH', 'Switzerland', 'EU'),
	('CI', 'Côte dIvoire', 'AF'),
	('CK', 'Cook Islands', 'OC'),
	('CL', 'Chile', 'SA'),
	('CM', 'Cameroon', 'AF'),
	('CN', 'China', 'AS'),
	('CO', 'Colombia', 'SA'),
	('CR', 'Costa Rica', 'NA'),
	('CU', 'Cuba', 'NA'),
	('CV', 'Cape Verde', 'AF'),
	('CX', 'Christmas Island', 'AS'),
	('CY', 'Cyprus', 'AS'),
	('CZ', 'Czech Republic', 'EU'),
	('DE', 'Germany', 'EU'),
	('DJ', 'Djibouti', 'AF'),
	('DK', 'Denmark', 'EU'),
	('DM', 'Dominica', 'NA'),
	('DO', 'Dominican Republic', 'NA'),
	('DZ', 'Algeria', 'AF'),
	('EC', 'Ecuador', 'SA'),
	('EE', 'Estonia', 'EU'),
	('EG', 'Egypt', 'AF'),
	('EH', 'Western Sahara', 'AF'),
	('ER', 'Eritrea', 'AF'),
	('ES', 'Spain', 'EU'),
	('ET', 'Ethiopia', 'AF'),
	('FI', 'Finland', 'EU'),
	('FJ', 'Fiji', 'OC'),
	('FK', 'Falkland Islands', 'SA'),
	('FM', 'Micronesia', 'OC'),
	('FO', 'Faroe Islands', 'EU'),
	('FR', 'France', 'EU'),
	('GA', 'Gabon', 'AF'),
	('GB', 'United Kingdom', 'EU'),
	('GD', 'Grenada', 'NA'),
	('GE', 'Georgia', 'AS'),
	('GF', 'French Guiana', 'SA'),
	('GG', 'Guernsey', 'EU'),
	('GH', 'Ghana', 'AF'),
	('GI', 'Gibraltar', 'EU'),
	('GL', 'Greenland', 'NA'),
	('GM', 'Gambia', 'AF'),
	('GN', 'Guinea', 'AF'),
	('GP', 'Guadeloupe', 'NA'),
	('GQ', 'Equatorial Guinea', 'AF'),
	('GR', 'Greece', 'EU'),
	('GS', 'South Georgia and South Sandwich Islands', 'AN'),
	('GT', 'Guatemala', 'NA'),
	('GU', 'Guam', 'OC'),
	('GW', 'Guinea-Bissau', 'AF'),
	('GY', 'Guyana', 'SA'),
	('HK', 'Hong Kong', 'AS'),
	('HM', 'Heard and McDonald Islands', 'AN'),
	('HN', 'Honduras', 'NA'),
	('HR', 'Croatia', 'EU'),
	('HT', 'Haiti', 'NA'),
	('HU', 'Hungary', 'EU'),
	('ID', 'Indonesia', 'AS'),
	('IE', 'Ireland', 'EU'),
	('IL', 'Israel', 'AS'),
	('IM', 'Isle of Man', 'EU'),
	('IN', 'India', 'AS'),
	('IO', 'British Indian Ocean Territory', 'AS'),
	('IQ', 'Iraq', 'AS'),
	('IR', 'Iran', 'AS'),
	('IS', 'Iceland', 'EU'),
	('IT', 'Italy', 'EU'),
	('JE', 'Jersey', 'EU'),
	('JM', 'Jamaica', 'NA'),
	('JO', 'Jordan', 'AS'),
	('JP', 'Japan', 'AS'),
	('KE', 'Kenya', 'AF'),
	('KG', 'Kyrgyzstan', 'AS'),
	('KH', 'Cambodia', 'AS'),
	('KI', 'Kiribati', 'OC'),
	('KM', 'Comoros', 'AF'),
	('KN', 'Saint Kitts and Nevis', 'NA'),
	('KP', 'Korea, North', 'AS'),
	('KR', 'Korea, South', 'AS'),
	('KW', 'Kuwait', 'AS'),
	('KY', 'Cayman Islands', 'NA'),
	('KZ', 'Kazakhstan', 'AS'),
	('LA', 'Laos', 'AS'),
	('LB', 'Lebanon', 'AS'),
	('LC', 'Saint Lucia', 'NA'),
	('LI', 'Liechtenstein', 'EU'),
	('LK', 'Sri Lanka', 'AS'),
	('LR', 'Liberia', 'AF'),
	('LS', 'Lesotho', 'AF'),
	('LT', 'Lithuania', 'EU'),
	('LU', 'Luxembourg', 'EU'),
	('LV', 'Latvia', 'EU'),
	('LY', 'Libya', 'AF'),
	('MA', 'Morocco', 'AF'),
	('MC', 'Monaco', 'EU'),
	('MD', 'Moldova', 'EU'),
	('ME', 'Montenegro', 'EU'),
	('MF', 'Saint Martin (French part)', 'NA'),
	('MG', 'Madagascar', 'AF'),
	('MH', 'Marshall Islands', 'OC'),
	('MK', 'Macedonia', 'EU'),
	('ML', 'Mali', 'AF'),
	('MM', 'Myanmar', 'AS'),
	('MN', 'Mongolia', 'AS'),
	('MO', 'Macau', 'AS'),
	('MP', 'Northern Mariana Islands', 'OC'),
	('MQ', 'Martinique', 'NA'),
	('MR', 'Mauritania', 'AF'),
	('MS', 'Montserrat', 'NA'),
	('MT', 'Malta', 'EU'),
	('MU', 'Mauritius', 'AF'),
	('MV', 'Maldives', 'AS'),
	('MW', 'Malawi', 'AF'),
	('MX', 'Mexico', 'NA'),
	('MY', 'Malaysia', 'AS'),
	('MZ', 'Mozambique', 'AF'),
	('NA', 'Namibia', 'AF'),
	('NC', 'New Caledonia', 'OC'),
	('NE', 'Niger', 'AF'),
	('NF', 'Norfolk Island', 'OC'),
	('NG', 'Nigeria', 'AF'),
	('NI', 'Nicaragua', 'NA'),
	('NL', 'Netherlands', 'EU'),
	('NO', 'Norway', 'EU'),
	('NP', 'Nepal', 'AS'),
	('NR', 'Nauru', 'OC'),
	('NU', 'Niue', 'OC'),
	('NZ', 'New Zealand', 'OC'),
	('OM', 'Oman', 'AS'),
	('PA', 'Panama', 'NA'),
	('PE', 'Peru', 'SA'),
	('PF', 'French Polynesia', 'OC'),
	('PG', 'Papua New Guinea', 'OC'),
	('PH', 'Philippines', 'AS'),
	('PK', 'Pakistan', 'AS'),
	('PL', 'Poland', 'EU'),
	('PM', 'Saint Pierre and Miquelon', 'NA'),
	('PN', 'Pitcairn', 'OC'),
	('PR', 'Puerto Rico', 'NA'),
	('PS', 'Palestine', 'AS'),
	('PT', 'Portugal', 'EU'),
	('PW', 'Palau', 'OC'),
	('PY', 'Paraguay', 'SA'),
	('QA', 'Qatar', 'AS'),
	('RE', 'Reunion', 'AF'),
	('RO', 'Romania', 'EU'),
	('RS', 'Serbia', 'EU'),
	('RU', 'Russian Federation', 'EU'),
	('RW', 'Rwanda', 'AF'),
	('SA', 'Saudi Arabia', 'AS'),
	('SB', 'Solomon Islands', 'OC'),
	('SC', 'Seychelles', 'AF'),
	('SD', 'Sudan', 'AF'),
	('SE', 'Sweden', 'EU'),
	('SG', 'Singapore', 'AS'),
	('SH', 'Saint Helena', 'AF'),
	('SI', 'Slovenia', 'EU'),
	('SJ', 'Svalbard and Jan Mayen Islands', 'EU'),
	('SK', 'Slovakia', 'EU'),
	('SL', 'Sierra Leone', 'AF'),
	('SM', 'San Marino', 'EU'),
	('SN', 'Senegal', 'AF'),
	('SO', 'Somalia', 'AF'),
	('SR', 'Suriname', 'SA'),
	('ST', 'Sao Tome and Principe', 'AF'),
	('SV', 'El Salvador', 'NA'),
	('SY', 'Syria', 'AS'),
	('SZ', 'Swaziland', 'AF'),
	('TC', 'Turks and Caicos Islands', 'NA'),
	('TD', 'Chad', 'AF'),
	('TF', 'French Southern Lands', 'AN'),
	('TG', 'Togo', 'AF'),
	('TH', 'Thailand', 'AS'),
	('TJ', 'Tajikistan', 'AS'),
	('TK', 'Tokelau', 'OC'),
	('TL', 'Timor-Leste', 'AS'),
	('TM', 'Turkmenistan', 'AS'),
	('TN', 'Tunisia', 'AF'),
	('TO', 'Tonga', 'OC'),
	('TR', 'Turkey', 'AS'),
	('TT', 'Trinidad and Tobago', 'NA'),
	('TV', 'Tuvalu', 'OC'),
	('TW', 'Taiwan', 'AS'),
	('TZ', 'Tanzania', 'AF'),
	('UA', 'Ukraine', 'EU'),
	('UG', 'Uganda', 'AF'),
	('UM', 'United States Minor Outlying Islands', 'OC'),
	('US', 'United States of America', 'NA'),
	('UY', 'Uruguay', 'SA'),
	('UZ', 'Uzbekistan', 'AS'),
	('VA', 'Vatican City', 'EU'),
	('VC', 'Saint Vincent and the Grenadines', 'NA'),
	('VE', 'Venezuela', 'SA'),
	('VG', 'Virgin Islands, British', 'NA'),
	('VI', 'Virgin Islands, U.S.', 'NA'),
	('VN', 'Vietnam', 'AS'),
	('VU', 'Vanuatu', 'OC'),
	('WF', 'Wallis and Futuna Islands', 'OC'),
	('WS', 'Samoa', 'OC'),
	('YE', 'Yemen', 'AS'),
	('YT', 'Mayotte', 'AF'),
	('ZA', 'South Africa', 'AF'),
	('ZM', 'Zambia', 'AF'),
	('ZW', 'Zimbabwe', 'AF');

ALTER TABLE CUSTOMERS
ADD FOREIGN KEY (country_id) REFERENCES LOCATIONS(country_id);

select * from locations
